export const SITE = {
  name: "Sun Evasion",
  tagline: "Voyagez avec le soleil",
  description: "Agence de voyage algérienne — séjours de rêve en Turquie et Tunisie",
  phone: "+213 770 60 47 71",
  whatsapp: "+213770604771",
  email: "contact@sunevasion.dz",
  address: "Alger, Algérie",
  instagram: "https://instagram.com/sunevasion.dz",
  facebook: "https://facebook.com/sunevasion.dz",
};

export const DESTINATIONS = [
  {
    id: "turquie",
    name: "Turquie",
    slug: "turquie",
    tagline: "Entre Orient et Occident",
    description:
      "Istanbul, Cappadoce, Antalya... Découvrez la magie ottomane, les plages turquoise et les paysages de conte de fées.",
    image: "/images/turkey-hero.jpg",
    color: "from-red-900 to-red-700",
    accent: "#dc2626",
    highlights: ["Istanbul", "Cappadoce", "Antalya", "Éphèse", "Pamukkale"],
    climate: "Méditerranéen",
    currency: "Livre turque (TRY)",
    language: "Turc",
    flag: "🇹🇷",
  },
  {
    id: "tunisie",
    name: "Tunisie",
    slug: "tunisie",
    tagline: "La Méditerranée à portée de main",
    description:
      "Djerba, Sousse, Carthage... Un pays de soleil, de culture millénaire et de plages de sable blanc.",
    image: "/images/tunisia-hero.jpg",
    color: "from-red-800 to-amber-700",
    accent: "#d97706",
    highlights: ["Djerba", "Sousse", "Tunis", "Carthage", "Sahara"],
    climate: "Méditerranéen / Désertique",
    currency: "Dinar tunisien (TND)",
    language: "Arabe / Français",
    flag: "🇹🇳",
  },
];

export const PACKAGES = [
  {
    id: "istanbul-5j",
    destination: "turquie",
    name: "Istanbul Splendeur",
    duration: "5 jours / 4 nuits",
    price: 89000,
    currency: "DZD",
    category: "Essentiel",
    image: "/images/istanbul.jpg",
    includes: [
      "Vol aller-retour Alger → Istanbul",
      "Hôtel 4★ centre-ville",
      "Petit-déjeuner buffet",
      "Transferts aéroport",
      "Guide francophone",
      "Croisière Bosphore",
    ],
    highlights: ["Sainte-Sophie", "Palais de Topkapi", "Grand Bazar", "Bosphore"],
    popular: false,
  },
  {
    id: "cappadoce-7j",
    destination: "turquie",
    name: "Cappadoce Magique",
    duration: "7 jours / 6 nuits",
    price: 145000,
    currency: "DZD",
    category: "Premium",
    image: "/images/cappadocia.jpg",
    includes: [
      "Vol aller-retour Alger → Istanbul",
      "Istanbul 3 nuits hôtel 4★",
      "Cappadoce 3 nuits cave hotel",
      "Tous les transferts",
      "Vol intérieur Istanbul ↔ Cappadoce",
      "Balade montgolfière en option",
      "Guide francophone exclusif",
    ],
    highlights: ["Vallée des Cheminées", "Göreme", "Montgolfière", "Derinkuyu"],
    popular: true,
  },
  {
    id: "antalya-7j",
    destination: "turquie",
    name: "Côte Turquoise",
    duration: "7 jours / 6 nuits",
    price: 129000,
    currency: "DZD",
    category: "Détente",
    image: "/images/antalya.jpg",
    includes: [
      "Vol aller-retour Alger → Antalya",
      "Hôtel 5★ tout-inclus bord de mer",
      "Transferts aéroport VIP",
      "Animation & sports nautiques",
      "Excursion Vieille Ville gratuite",
    ],
    highlights: ["Plages d'Antalya", "Konyaaltı", "Vieille ville", "Waterfalls"],
    popular: false,
  },
  {
    id: "djerba-5j",
    destination: "tunisie",
    name: "Djerba Paradis",
    duration: "5 jours / 4 nuits",
    price: 65000,
    currency: "DZD",
    category: "Essentiel",
    image: "/images/djerba.jpg",
    includes: [
      "Vol aller-retour Alger → Djerba",
      "Hôtel 4★ bord de mer",
      "Demi-pension",
      "Transferts aéroport",
      "Excursion Houmt Souk",
    ],
    highlights: ["Plage Sidi Mahrez", "Houmt Souk", "Guellala", "Midoun"],
    popular: true,
  },
  {
    id: "sousse-7j",
    destination: "tunisie",
    name: "Sousse & Carthage",
    duration: "7 jours / 6 nuits",
    price: 95000,
    currency: "DZD",
    category: "Culture",
    image: "/images/sousse.jpg",
    includes: [
      "Vol aller-retour Alger → Tunis",
      "Sousse 4 nuits hôtel 5★",
      "Tunis 2 nuits hôtel 4★",
      "Pension complète",
      "Tous les transferts",
      "Visite Carthage guidée",
      "Visite Médina de Tunis",
    ],
    highlights: ["Médina Sousse", "Carthage", "Sidi Bou Saïd", "Bardo"],
    popular: false,
  },
];
