export type Hotel = {
  id: string;
  name: string;
  country: "turquie" | "tunisie" | "arabie";
  city: string;
  stars: 3 | 4 | 5;
  category: "budget" | "midrange" | "luxury";
  pricePerNight: number; // EUR B2B net
  commission: number; // %
  website: string;
  email: string;
  phone?: string;
  description: string;
  advantages: string[];
  conditions: string[];
  groupMin: number; // minimum pax for B2B
  image: string;
  rating: number; // /10
  reviewCount: number;
  tags: string[];
  hasContract: boolean;
};

export const HOTELS: Hotel[] = [
  // ─── TURQUIE — Istanbul ───
  {
    id: "divan-istanbul",
    name: "Divan Istanbul",
    country: "turquie",
    city: "Istanbul",
    stars: 5,
    category: "luxury",
    pricePerNight: 180,
    commission: 15,
    website: "https://www.divan.com.tr",
    email: "groups@divan.com.tr",
    phone: "+90 212 315 5500",
    description: "Hôtel 5★ emblématique d'Istanbul, idéalement situé à Nişantaşı. Programme Tour Operator actif avec allotement garanti.",
    advantages: ["Allotement garanti 30 chambres", "Commission 15% sur tarif net", "Guide francophone dédié", "Transferts aéroport inclus groupes", "Petit-déjeuner buffet offert"],
    conditions: ["Minimum 10 pax", "Confirmation 21 jours avant", "Acompte 30% à la réservation", "Annulation gratuite J-14"],
    groupMin: 10,
    image: "/images/istanbul.webp",
    rating: 9.1,
    reviewCount: 2847,
    tags: ["Centre-ville", "Vue Bosphore", "Spa", "Restaurant gastronomique"],
    hasContract: false,
  },
  {
    id: "cvk-park-bosphorus",
    name: "CVK Park Bosphorus Hotel",
    country: "turquie",
    city: "Istanbul",
    stars: 5,
    category: "luxury",
    pricePerNight: 210,
    commission: 12,
    website: "https://www.cvkhotels.com",
    email: "sales@cvkhotels.com",
    phone: "+90 212 973 1234",
    description: "Vue panoramique sur le Bosphore, congrès et groupes. L'un des hôtels les plus demandés par les agences algériennes.",
    advantages: ["Vue Bosphore directe", "Salle de conférence 500 pers.", "Commission 12% nets", "Visa support letters", "Menu halal sur demande"],
    conditions: ["Minimum 15 pax pour tarif groupe", "Acompte 40%", "Annulation J-21", "Contrat annuel disponible"],
    groupMin: 15,
    image: "/images/istanbul.webp",
    rating: 9.3,
    reviewCount: 1523,
    tags: ["Vue Bosphore", "Groupes", "Halal friendly", "Piscine"],
    hasContract: false,
  },
  {
    id: "holiday-inn-sisli",
    name: "Holiday Inn Istanbul Şişli",
    country: "turquie",
    city: "Istanbul",
    stars: 4,
    category: "midrange",
    pricePerNight: 95,
    commission: 18,
    website: "https://www.ihg.com",
    email: "istanbul.sisli@ihg.com",
    phone: "+90 212 368 4000",
    description: "Idéal pour les groupes budget à mid-range. Excellent rapport qualité/prix, programme agences parmi les plus généreux d'Istanbul.",
    advantages: ["Commission 18% (la plus haute)", "Allotement 50 chambres garanti", "Transferts inclus >20 pax", "Petit-déjeuner buffet", "Parking gratuit bus"],
    conditions: ["Minimum 8 pax", "Confirmation 14 jours", "Acompte 25%", "Annulation gratuite J-7"],
    groupMin: 8,
    image: "/images/istanbul.webp",
    rating: 8.6,
    reviewCount: 3201,
    tags: ["Rapport Q/P", "Centre commercial", "Métro direct", "Groupes"],
    hasContract: false,
  },

  // ─── TURQUIE — Cappadoce ───
  {
    id: "sultan-cave-suites",
    name: "Sultan Cave Suites",
    country: "turquie",
    city: "Cappadoce",
    stars: 4,
    category: "midrange",
    pricePerNight: 130,
    commission: 15,
    website: "https://www.sultancavesuites.com",
    email: "info@sultancavesuites.com",
    phone: "+90 384 271 2900",
    description: "Cave hotel authentique de Göreme avec terrasse panoramique. Expérience unique très demandée par les clients algériens.",
    advantages: ["Expérience grotte unique", "Terrasse panoramique montgolfières", "Commission 15%", "Petit-déjeuner traditionnel turc", "Photos professionnelles offertes"],
    conditions: ["Minimum 6 chambres", "Réservation 30 jours avant", "Acompte 50%", "Annulation J-14"],
    groupMin: 6,
    image: "/images/cappadoce.webp",
    rating: 9.4,
    reviewCount: 4156,
    tags: ["Cave hotel", "Montgolfière", "Vue panoramique", "Romantique"],
    hasContract: false,
  },

  // ─── TURQUIE — Antalya ───
  {
    id: "titanic-beach-antalya",
    name: "Titanic Beach Lara",
    country: "turquie",
    city: "Antalya",
    stars: 5,
    category: "luxury",
    pricePerNight: 160,
    commission: 12,
    website: "https://www.titanichotels.com",
    email: "groups@titanichotels.com",
    phone: "+90 242 310 5000",
    description: "Resort 5★ tout-inclus ultra-complet sur la plage de Lara. L'hôtel de référence pour les séjours détente en Turquie.",
    advantages: ["Tout-inclus premium", "5 piscines + plage privée", "Commission 12% nets", "Animation 24h", "Baby-club et teens-club"],
    conditions: ["Minimum 20 pax pour tarif groupe", "Acompte 35%", "Annulation J-21", "Vol charter possible"],
    groupMin: 20,
    image: "/images/antalya.webp",
    rating: 9.0,
    reviewCount: 6748,
    tags: ["All-inclusive", "Plage", "Famille", "Resort"],
    hasContract: false,
  },
  {
    id: "rixos-premium-antalya",
    name: "Rixos Premium Belek",
    country: "turquie",
    city: "Antalya",
    stars: 5,
    category: "luxury",
    pricePerNight: 220,
    commission: 10,
    website: "https://www.rixos.com",
    email: "belek@rixos.com",
    phone: "+90 242 710 0000",
    description: "Le palace de référence en Turquie, ultra-luxe tout-inclus. Clientèle haut de gamme, idéal pour les forfaits VIP.",
    advantages: ["Ultra all-inclusive", "Golf 18 trous inclus", "Spa 6000m²", "Commission 10% + bonus annuel", "Accès VIP pour groupes"],
    conditions: ["Minimum 30 pax", "Contrat annuel requis", "Acompte 40%", "Annulation J-30"],
    groupMin: 30,
    image: "/images/antalya.webp",
    rating: 9.5,
    reviewCount: 4231,
    tags: ["Ultra-luxe", "Golf", "Spa", "VIP"],
    hasContract: false,
  },

  // ─── TUNISIE — Djerba ───
  {
    id: "radisson-blu-djerba",
    name: "Radisson Blu Resort Djerba",
    country: "tunisie",
    city: "Djerba",
    stars: 5,
    category: "luxury",
    pricePerNight: 120,
    commission: 15,
    website: "https://www.radissonhotels.com",
    email: "reservations.djerba@radissonblu.com",
    phone: "+216 75 757 000",
    description: "Resort 5★ sur la plage de Sidi Mahrez. Programme agences parmi les plus compétitifs de Tunisie.",
    advantages: ["Commission 15% + bonus fidélité", "Plage privée 400m", "Demi-pension ou all-inclusive", "Transferts gratuits >15 pax", "Animateur francophone"],
    conditions: ["Minimum 10 pax", "Confirmation 14 jours", "Acompte 30%", "Annulation gratuite J-10"],
    groupMin: 10,
    image: "/images/djerba.webp",
    rating: 8.8,
    reviewCount: 2156,
    tags: ["Plage", "All-inclusive", "Famille", "Sport nautique"],
    hasContract: false,
  },
  {
    id: "djerba-plaza",
    name: "Djerba Plaza Hotel & Spa",
    country: "tunisie",
    city: "Djerba",
    stars: 4,
    category: "midrange",
    pricePerNight: 75,
    commission: 20,
    website: "https://www.djerba-plaza.com",
    email: "commercial@djerba-plaza.com",
    phone: "+216 75 657 000",
    description: "Hôtel 4★ très prisé des agences algériennes. Commission parmi les plus élevées de l'île + conditions souples.",
    advantages: ["Commission 20% — la meilleure de Djerba", "Allotement 60 chambres", "Demi-pension incluse", "Transferts offerts", "Soirées folkloriques"],
    conditions: ["Minimum 6 pax", "Confirmation 10 jours", "Acompte 20%", "Annulation J-7 gratuite"],
    groupMin: 6,
    image: "/images/djerba.webp",
    rating: 8.5,
    reviewCount: 3892,
    tags: ["Rapport Q/P", "Soirées", "Spa", "Piscine"],
    hasContract: false,
  },
  {
    id: "hasdrubal-djerba",
    name: "Hasdrubal Thalassa & Spa",
    country: "tunisie",
    city: "Djerba",
    stars: 5,
    category: "luxury",
    pricePerNight: 140,
    commission: 13,
    website: "https://www.hasdrubal.com",
    email: "sales@hasdrubal.com",
    phone: "+216 75 745 444",
    description: "Resort thalasso haut de gamme avec spa marin. Clientèle aisée, idéal pour les forfaits bien-être.",
    advantages: ["Thalasso & spa inclus", "Architecture andalouse unique", "Commission 13%", "Soins spa pour groupes", "Restaurant gastronomique"],
    conditions: ["Minimum 12 pax", "Acompte 35%", "Annulation J-14", "Contrat préférentiel annuel"],
    groupMin: 12,
    image: "/images/djerba.webp",
    rating: 9.1,
    reviewCount: 1847,
    tags: ["Thalasso", "Bien-être", "Gastronomie", "Luxe"],
    hasContract: false,
  },

  // ─── TUNISIE — Sousse ───
  {
    id: "marhaba-palace-sousse",
    name: "Marhaba Palace",
    country: "tunisie",
    city: "Sousse",
    stars: 5,
    category: "luxury",
    pricePerNight: 110,
    commission: 15,
    website: "https://www.marhabahotels.com",
    email: "groups@marhabahotels.com",
    phone: "+216 73 226 888",
    description: "Hôtel 5★ en bord de mer à Sousse. Idéal pour combiner culture (Médina, Carthage) et plage. Très actif avec les agences.",
    advantages: ["Commission 15%", "All-inclusive disponible", "Plage privée", "Excursions Carthage organisées", "Guide francophone"],
    conditions: ["Minimum 10 pax", "Confirmation 14 jours", "Acompte 30%", "Annulation J-10"],
    groupMin: 10,
    image: "/images/sousse.webp",
    rating: 8.7,
    reviewCount: 2934,
    tags: ["Culture", "Plage", "All-inclusive", "Excursions"],
    hasContract: false,
  },
  {
    id: "iberostar-averroes",
    name: "Iberostar Averroes Hammamet",
    country: "tunisie",
    city: "Hammamet",
    stars: 4,
    category: "midrange",
    pricePerNight: 85,
    commission: 17,
    website: "https://www.iberostar.com",
    email: "hammamet@iberostar.com",
    phone: "+216 72 280 777",
    description: "Resort Iberostar en tout-inclus à Hammamet. Marque internationale avec programme agences structuré et commissions régulières.",
    advantages: ["Commission 17% garantie", "Tout-inclus certifié", "Marque internationale reconnue", "Programme fidélité agence", "Confirmation rapide"],
    conditions: ["Minimum 8 pax", "Acompte 25%", "Annulation J-14", "Contrat Iberostar Pro disponible"],
    groupMin: 8,
    image: "/images/sousse.webp",
    rating: 8.4,
    reviewCount: 5621,
    tags: ["All-inclusive", "Famille", "Animation", "Sport"],
    hasContract: false,
  },
];

export const COUNTRIES = [
  { value: "all", label: "Toutes les destinations" },
  { value: "turquie", label: "🇹🇷 Turquie" },
  { value: "tunisie", label: "🇹🇳 Tunisie" },
];

export const CITIES: Record<string, string[]> = {
  turquie: ["Istanbul", "Cappadoce", "Antalya"],
  tunisie: ["Djerba", "Sousse", "Hammamet"],
};
